print("Welcome to the BMI calculator")
height= float(input("What is your height (in meters)?\n"))
weight = float(input("What is your weight (in kilograms)?\n"))
bmi = weight/ (height ** 2)
print(f"Your BMI is: {bmi:.2f}")